import { getColors  } from "./color"

export default function getTheme({ theme, name }): Object {

  const colors = getColors(theme)

  return {
    "name": name,
    "type": "light",
    "colors": {
      "activityBar.background": colors.primary,
      "activityBar.border": colors.text,
      "activityBar.dropBackground": colors.shadow,
      "activityBar.foreground": colors.text,
      "activityBarBadge.background": colors.hint,
      "activityBarBadge.foreground": colors.text,
      "badge.background": colors.hint,
      "badge.foreground": colors.text,
      "button.background": colors.primary,
      "button.foreground": colors.text,
      "editor.background": colors.editor,
      "editor.foreground": colors.text,
      "editor.hoverHighlightBackground": colors.editor,
      "editor.inactiveSelectionBackground": colors.inactive,
      "editor.selectionBackground": colors.selection,
      "editor.selectionHighlightBackground": colors.selection,
      "editorGroupHeader.tabsBackground": colors.primary,
      "input.background": colors.primary,
      "input.border": colors.text,
      "input.foreground": colors.text,
      "input.placeholderForeground": colors.text,
      "panel.background": colors.editor,
      "selection.background": colors.editor,
      "sideBar.dropBackground": colors.shadow,
      "sideBar.background": colors.primary,
      "sideBar.border": colors.text,
      "sideBarSectionHeader.background": colors.primary,
      "sideBar.foreground": colors.text,
      "scrollbarSlider.activeBackground": colors.shadow,
      "scrollbarSlider.background": colors.shadow,
      "scrollbarSlider.hoverBackground": colors.shadow,
      "statusBar.background": colors.primary,
      "statusBar.border": colors.text,
      "statusBar.foreground": colors.text,
      "tab.activeBackground": colors.primary,
      "tab.activeBorder": colors.text,
      "tab.activeBorderTop": colors.primary,
      "tab.activeForeground": colors.text,
      "tab.inactiveBackground": colors.primary,
      "tab.border": colors.primary,
      "tab.hoverBackground": colors.editor,
      "tab.hoverBorder": colors.primary,
      "tab.inactiveForeground": colors.text,
      "list.focusHighlightForeground": colors.primary,
      "quickInputList.focusForeground": colors.primary,
      "editorSuggestWidget.selectedForeground": colors.primary,
      "editorBracketHighlight.foreground1": colors.text,
      "editorBracketHighlight.foreground2": colors.text,
      "editorBracketHighlight.foreground3": colors.text,
      "editorBracketHighlight.foreground4": colors.text,
      "editorBracketHighlight.foreground5": colors.text,
      "editorBracketHighlight.foreground6": colors.text,
      "editorBracketHighlight.unexpectedBracket.foreground": colors.error,
      "terminal.foreground": colors.text,
      "terminal.background": colors.editor,
      "terminal.ansiBrightBlack": colors.inactive,
      "terminal.ansiBrightBlue": colors.text,
      "terminal.ansiBrightCyan": colors.text,
      "terminal.ansiBrightGreen": colors.text,
      "terminal.ansiBrightMagenta": colors.text,
      "terminal.ansiBrightRed": colors.text,
      "terminal.ansiBrightWhite": colors.text,
      "terminal.ansiBrightYellow": colors.text,
      "terminal.ansiBlack": colors.text,
      "terminal.ansiBlue": colors.text,
      "terminal.ansiCyan": colors.text,
      "terminal.ansiGreen": colors.text,
      "terminal.ansiMagenta": colors.text,
      "terminal.ansiRed": colors.text,
      "terminal.ansiWhite": colors.text,
      "terminal.ansiYellow": colors.text
    }
  }
}
